version: '3.3'

services:

  sql:
    image: sc9xm1sql
    build:
      context: .\xm1\sql

  cm:
    image: sc9xm1cm
    build:
      context: .\xm1\cm
    ports: 
      - 80:80
    links:
      - sql
