version: '3.3'

services:

  sql:
    image: sc9xm1sql
    build:
      context: .\sitecore-sql

  cm:
    image: sc9xm1cm
    build:
      context: .\sitecore-xm1
    ports: 
      - 80:80
    links:
      - sql
